### PR TITLE
Uploading logo and info.json files

### PR DESCRIPTION
**Pull request by fliferteam**

### CODE REVIEW

**Comment by fliferteam** [comment]
@LukeBogTools

**Comment by fliferteam** [comment]
@LukeBogTools

**Comment by lukebogtools** [comment]
Hi, the folder name needs to be in the checksum'd format.

Example:  0x166DAEE763902dA67984E38BaA478a63f55CC25b
Not: 0x166daee763902da67984e38baa478a63f55cc25b

**Comment by fliferteam** [comment]
Hello Luke,

We deleted the old folder, and created a new folder in checksum format.
Thank you

**Pull request closed without merging**
